spring:
  batch:
    jdbc:
      table-prefix: BOOT3_BATCH_
      initialize-schema: ALWAYS
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://127.0.0.1:58831/dataflow # post changes after each service expose as i am using the minikube service instead of port fwd
    username: scdf
    password: scdfpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
